# Numpy 3D arrays

In [1]:
import numpy as np

d3 = np.arange(50).reshape(2,5,5)
d3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

Indexing 3D

In [2]:
d3[1,2,1]

36

In [3]:
d3[1]

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [4]:
d3[0:,2:,1:3]

array([[[11, 12],
        [16, 17],
        [21, 22]],

       [[36, 37],
        [41, 42],
        [46, 47]]])

In [5]:
#d3[1:2,4:5,0:5]
d3[1:,4:,:]

array([[[45, 46, 47, 48, 49]]])

In [6]:
### d3[0:,2:4,1:3]

In [7]:
d3[1,:,3:4]

array([[28],
       [33],
       [38],
       [43],
       [48]])

# BroadCasting

In [8]:
x = np.array([[1,2,3]])  #(1,3)
y = np.array([[1],[2],[3]])#(3,1)
x+y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [9]:
x.shape, y.shape

((1, 3), (3, 1))

In [10]:
x,y=np.broadcast_arrays(x,y)
x 

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [11]:
y

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [12]:
x+y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

# Pandas

# Pandas data structure
Series
DataFrame

# Series

In [13]:
import pandas as pd

In [14]:
s = pd.Series([111,222,333,444,555,666,777])
s  # pandas series object

0    111
1    222
2    333
3    444
4    555
5    666
6    777
dtype: int64

In [15]:
# labels/index and values

In [16]:
#getting a single series value

s[4]

555

In [17]:
#getting a single series value
s[[5,0,3,1]]

5    666
0    111
3    444
1    222
dtype: int64

In [18]:
# updating a series value
s[3]= 1000
# updating multiple series value

s[[2,4,0]]=[9999,7777,1111]

In [19]:
s

0    1111
1     222
2    9999
3    1000
4    7777
5     666
6     777
dtype: int64

In [20]:
# deleting a value in series

del s[4]
s

0    1111
1     222
2    9999
3    1000
5     666
6     777
dtype: int64

In [21]:
# deleting multiple values in a series
del s[[0,2,6]]

# not allowed

TypeError: '[0, 2, 6]' is an invalid key

In [22]:
s[1234]= 45676878
s[[123,345,678]]=[23,23,23]
#not allowed

ValueError: [123 345 678] not contained in the index

In [23]:
s

0           1111
1            222
2           9999
3           1000
5            666
6            777
1234    45676878
dtype: int64

In [24]:
s1 = pd.Series([100,200,300,400], index=["apples", "oranges","bananas", "grapes"])

In [25]:
s1

apples     100
oranges    200
bananas    300
grapes     400
dtype: int64

# Creating a series using a dictionary

In [26]:
aDic = {"name":"Nasir Hussain", "Class":"AI", "Time":"5-9"}

In [27]:
aDic

{'name': 'Nasir Hussain', 'Class': 'AI', 'Time': '5-9'}

In [28]:
s2 = pd.Series(aDic)
s2

name     Nasir Hussain
Class               AI
Time               5-9
dtype: object

In [29]:
s3 = pd.Series(s1, index=["mango", "oranges","bananas", "grapes"])

In [30]:
s3

mango        NaN
oranges    200.0
bananas    300.0
grapes     400.0
dtype: float64

In [31]:
s3["mango"]=100

In [32]:
s3

mango      100.0
oranges    200.0
bananas    300.0
grapes     400.0
dtype: float64

In [33]:
s3.values

array([100., 200., 300., 400.])

In [34]:
s3.index

Index(['mango', 'oranges', 'bananas', 'grapes'], dtype='object')

In [35]:
s3[s3>200]

bananas    300.0
grapes     400.0
dtype: float64

In [36]:
s3>200

mango      False
oranges    False
bananas     True
grapes      True
dtype: bool

In [37]:
"Mango" in s3

False

In [38]:
s4= pd.Series(s3.values, index=[22,33,44,55])

In [39]:
s4

22    100.0
33    200.0
44    300.0
55    400.0
dtype: float64

In [40]:
s3

mango      100.0
oranges    200.0
bananas    300.0
grapes     400.0
dtype: float64

In [41]:
s3+s4

/home/nasir/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py:3772: RuntimeWarning: '<' not supported between instances of 'str' and 'int', sort order is undefined for incomparable objects
  return this.join(other, how=how, return_indexers=return_indexers)


mango     NaN
oranges   NaN
bananas   NaN
grapes    NaN
22        NaN
33        NaN
44        NaN
55        NaN
dtype: float64

# DataFrame

In [42]:
df = pd.DataFrame([123,234,345,456])
df

0
0  123
1  234
2  345
3  456

In [43]:
df = pd.DataFrame(["Red","Green", "Blue"],index=['v1','v2','v3'])
df

0
v1    Red
v2  Green
v3   Blue

In [44]:
df = pd.DataFrame(["Red","Green", "Blue"],index=['v1','v2','v3'],columns=["Colors"])
df

Colors
v1    Red
v2  Green
v3   Blue

# Creating a Data Frame from a dictionary

In [45]:
score = {"Ai for EO":[76,78,89,90,83,82,87,89,90,99],
         "Python1"  :[67,78,76,75,89,90,54,78,87,45],
         "Python2"  :[78,76,79,56,34,89,45,78,91,89]
        }

In [46]:
df = pd.DataFrame(score,index=["Nasir", "Asad","Ahmed",
                               "Abdullah","Faraz", "Zaid",
                               "Ali", "Khan", 'Faisal', 
                               "Fahad"])
df

Ai for EO  Python1  Python2
Nasir            76       67       78
Asad             78       78       76
Ahmed            89       76       79
Abdullah         90       75       56
Faraz            83       89       34
Zaid             82       90       89
Ali              87       54       45
Khan             89       78       78
Faisal           90       87       91
Fahad            99       45       89

In [47]:
df.head(3)

Ai for EO  Python1  Python2
Nasir         76       67       78
Asad          78       78       76
Ahmed         89       76       79

In [48]:
df.tail(3)

Ai for EO  Python1  Python2
Khan           89       78       78
Faisal         90       87       91
Fahad          99       45       89

In [49]:
df

Ai for EO  Python1  Python2
Nasir            76       67       78
Asad             78       78       76
Ahmed            89       76       79
Abdullah         90       75       56
Faraz            83       89       34
Zaid             82       90       89
Ali              87       54       45
Khan             89       78       78
Faisal           90       87       91
Fahad            99       45       89

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, Nasir to Fahad
Data columns (total 3 columns):
Ai for EO    10 non-null int64
Python1      10 non-null int64
Python2      10 non-null int64
dtypes: int64(3)
memory usage: 320.0+ bytes


In [51]:
df.describe()

Ai for EO    Python1    Python2
count  10.000000  10.000000  10.000000
mean   86.300000  73.900000  71.500000
std     6.733828  14.820781  19.727308
min    76.000000  45.000000  34.000000
25%    82.250000  69.000000  61.000000
50%    88.000000  77.000000  78.000000
75%    89.750000  84.750000  86.500000
max    99.000000  90.000000  91.000000

In [52]:
#data = pd.read_csv("banknotes.csv")

In [53]:
df['Python1']

Nasir       67
Asad        78
Ahmed       76
Abdullah    75
Faraz       89
Zaid        90
Ali         54
Khan        78
Faisal      87
Fahad       45
Name: Python1, dtype: int64

In [54]:
df['Ai for EO']

Nasir       76
Asad        78
Ahmed       89
Abdullah    90
Faraz       83
Zaid        82
Ali         87
Khan        89
Faisal      90
Fahad       99
Name: Ai for EO, dtype: int64

In [55]:
df.loc[['Abdullah','Fahad']]['Python1']

Abdullah    75
Fahad       45
Name: Python1, dtype: int64

In [56]:
df

Ai for EO  Python1  Python2
Nasir            76       67       78
Asad             78       78       76
Ahmed            89       76       79
Abdullah         90       75       56
Faraz            83       89       34
Zaid             82       90       89
Ali              87       54       45
Khan             89       78       78
Faisal           90       87       91
Fahad            99       45       89

In [57]:
df["extra"]=range(10)
df

Ai for EO  Python1  Python2  extra
Nasir            76       67       78      0
Asad             78       78       76      1
Ahmed            89       76       79      2
Abdullah         90       75       56      3
Faraz            83       89       34      4
Zaid             82       90       89      5
Ali              87       54       45      6
Khan             89       78       78      7
Faisal           90       87       91      8
Fahad            99       45       89      9

In [58]:
del df["extra"]
df

Ai for EO  Python1  Python2
Nasir            76       67       78
Asad             78       78       76
Ahmed            89       76       79
Abdullah         90       75       56
Faraz            83       89       34
Zaid             82       90       89
Ali              87       54       45
Khan             89       78       78
Faisal           90       87       91
Fahad            99       45       89

In [59]:
df["Total"]=df["Ai for EO"] + df["Python1"] + df['Python2']
df

Ai for EO  Python1  Python2  Total
Nasir            76       67       78    221
Asad             78       78       76    232
Ahmed            89       76       79    244
Abdullah         90       75       56    221
Faraz            83       89       34    206
Zaid             82       90       89    261
Ali              87       54       45    186
Khan             89       78       78    245
Faisal           90       87       91    268
Fahad            99       45       89    233

In [60]:
# df["Status"]=np.where(df['Total']>200,"Pass","Fail")
# df



In [61]:
df["Status"]=["Pass" if marks>200 else "Fails" for marks in df['Total']]

In [62]:
df

Ai for EO  Python1  Python2  Total Status
Nasir            76       67       78    221   Pass
Asad             78       78       76    232   Pass
Ahmed            89       76       79    244   Pass
Abdullah         90       75       56    221   Pass
Faraz            83       89       34    206   Pass
Zaid             82       90       89    261   Pass
Ali              87       54       45    186  Fails
Khan             89       78       78    245   Pass
Faisal           90       87       91    268   Pass
Fahad            99       45       89    233   Pass

In [63]:
df['RevisedStatus']=np.where(((df['Ai for EO']>=50) & (df["Python1"]>=50) & (df["Python2"]>=50)),"Pass","Fail")

In [64]:
df

Ai for EO  Python1  Python2  Total Status RevisedStatus
Nasir            76       67       78    221   Pass          Pass
Asad             78       78       76    232   Pass          Pass
Ahmed            89       76       79    244   Pass          Pass
Abdullah         90       75       56    221   Pass          Pass
Faraz            83       89       34    206   Pass          Fail
Zaid             82       90       89    261   Pass          Pass
Ali              87       54       45    186  Fails          Fail
Khan             89       78       78    245   Pass          Pass
Faisal           90       87       91    268   Pass          Pass
Fahad            99       45       89    233   Pass          Fail

In [65]:
df['newStatus']=["Pass" if (ai>=50) & (p1>=50) & (p2>=50) else "Fail" for ai,p1,p2 in zip(df["Ai for EO"], df['Python1'],df["Python2"])]

In [66]:
df

Ai for EO  Python1  Python2  Total Status RevisedStatus newStatus
Nasir            76       67       78    221   Pass          Pass      Pass
Asad             78       78       76    232   Pass          Pass      Pass
Ahmed            89       76       79    244   Pass          Pass      Pass
Abdullah         90       75       56    221   Pass          Pass      Pass
Faraz            83       89       34    206   Pass          Fail      Fail
Zaid             82       90       89    261   Pass          Pass      Pass
Ali              87       54       45    186  Fails          Fail      Fail
Khan             89       78       78    245   Pass          Pass      Pass
Faisal           90       87       91    268   Pass          Pass      Pass
Fahad            99       45       89    233   Pass          Fail      Fail

In [67]:
x = [1,2,3,4]
y = ['a','b','c','d']
z = zip(x,y)


In [68]:
for x,y in z:
    print(x,y)

1 a
2 b
3 c
4 d


# 13-10-2019

In [77]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [78]:
frame3 = pd.DataFrame(pop)

In [79]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [84]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         
         'Nevada': frame3['Nevada'][:2]}
pdata = pd.DataFrame(pdata)
pdata

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [85]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [86]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [87]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

# Index Objects

In [88]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [89]:
obj

a    0
b    1
c    2
dtype: int64

In [90]:
index = obj.index

In [91]:
index

Index(['a', 'b', 'c'], dtype='object')

In [92]:
index[1:]

Index(['b', 'c'], dtype='object')

# 5.2 Essential Functionality

In [94]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [95]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [97]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])


a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [125]:
obj2['e']=100
obj2

a     -5.3
b      7.2
c      3.6
d      4.5
e    100.0
dtype: float64

In [114]:
bj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0,  4,9])

In [115]:
obj3

0      blue
4    purple
9    yellow
dtype: object

In [116]:
obj3.reindex(range(6))

0      blue
1       NaN
2       NaN
3       NaN
4    purple
5       NaN
dtype: object

In [118]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2      blue
3      blue
4    purple
5    purple
dtype: object

In [109]:
obj3.reindex(range(6), method='bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [119]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index=['a', 'c', 'd'],
                    columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [121]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2


Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [122]:
states = ['Texas', 'Utah', 'California']

In [123]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [129]:
newFrame = frame.reindex(index=['a', 'b', 'c', 'd'],
                        columns=['Texas', 'Utah', 'California',
                                 "NewYork"])
newFrame

Texas  Utah  California  NewYork
a    1.0   NaN         2.0      NaN
b    NaN   NaN         NaN      NaN
c    4.0   NaN         5.0      NaN
d    7.0   NaN         8.0      NaN

In [130]:
newFrame['NewYork']['b']=800

In [131]:
newFrame

Texas  Utah  California  NewYork
a    1.0   NaN         2.0      NaN
b    NaN   NaN         NaN    800.0
c    4.0   NaN         5.0      NaN
d    7.0   NaN         8.0      NaN

In [132]:
frame.loc[['a', 'b', 'c', 'd'], states]

/home/nasir/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

# Dropping Entries from an Axis

In [133]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [138]:
obj.drop('c',inplace=True)

In [139]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [140]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [141]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [142]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [145]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [146]:
df = pd.read_csv('data.csv')

In [153]:
df

Student Code  Degree                    Student Name  Mid  Quiz 1  \
0    022-14-19987  BS(CS)                     Abdul Basit   28     8.0   
1   022-14-110233  BS(CS)                     Adeel Ahmed   17     NaN   
2   022-14-110585  BS(CS)                    Afrah Zareen   18     5.0   
3    022-14-19718  BS(CS)                  Ahmed Ali Raza   14     7.0   
4   022-14-110648  BS(CS)                 Ahsan Ali Vohra   27     7.0   
5   022-14-110232  BS(CS)                     Ameer Hamza   25     9.0   
6   022-14-110588  BS(CS)                   Anas Ali Khan   28     5.0   
7   022-14-110388  BS(CS)                Aneebullah Niazi   26     9.0   
8   022-14-110601  BS(CS)                  Areesha Sohail   19     9.0   
9   022-14-110599  BS(CS)                         Arsalan   28     8.0   
10  022-14-110214  BS(CS)             Fatima Haider Warsi   30     8.0   
11  022-14-110591  BS(CS)                     Habib Ullah   28     8.0   
12  022-15-110994  BS(CS)             Hafiza Tooba Akbani   23     7.0   
13  022-14-110600  BS(CS)              Hamza Abdul Jabbar   24     8.0   
14  022-14-110389  BS(CS)                   Hareem Afshan   21     7.0   
15   022-14-19916  BS(CS)                    Haseeb Sajid   18     NaN   
16  022-14-110596  BS(CS)                    Hassam Ahmed   23     5.0   
17  022-14-110396  BS(CS)                    Khalid Anwer   20     8.0   
18  022-14-110223  BS(CS)                   Madiha Jabeen   16     5.0   
19  022-14-110222  BS(CS)                 Mohammad Hunain   27     9.0   
20  022-14-110412  BS(CS)                  Muhammad Aamir   24     7.0   
21  022-14-110593  BS(CS)  Muhammad Abdul Rehman Siddiqui   20     9.0   
22  022-14-110398  BS(CS)               Muhammad Abdullah   20     7.0   
23   022-14-19983  BS(CS)              Muhammad Ali Iqbal   26     5.0   
24  022-14-110215  BS(CS)                  Muhammad Bilal   28     5.0   
25  022-14-110105  BS(CS)                  Muhammad Faraz   26     9.0   
26  022-14-110370  BS(CS)         Muhammad Ghazali Faridi   27     6.0   
27  022-14-110452  BS(CS)             Muhammad Osama Khan   27     8.0   
28  022-14-110387  BS(CS)          Muhammad Saqib Intizar   22     6.0   
29  022-14-110217  BS(CS)       Muhammad Shahroz Khurshid   17     7.0   
30  022-14-110401  BS(CS)                 Muhammad Shozab   23     8.0   
31  022-14-110231  BS(CS)           Muhammad Taha Hasnain   27     7.0   
32  022-14-110035  BS(CS)           Muhammad Wajahat Khan    9     NaN   
33   022-14-19919  BS(CS)            Muhammad Younus Baig   20     4.0   
34  022-14-110413  BS(CS)                Nazeer Bin Zafar   25     9.0   
35   022-14-19923  BS(CS)                      Rabi Ahmed   20     8.0   
36  022-14-110582  BS(CS)                      Rida Nasim   25     9.0   
37  022-14-110230  BS(CS)                   Sadaf Nosheen   27     9.0   
38  022-14-110229  BS(CS)                Sadaquat Rafique    9     6.0   
39  022-14-110107  BS(CS)                     Sania Iqbal   28     4.0   
40  022-14-110584  BS(CS)                     Sharif Taqi   27     9.0   
41  022-14-110225  BS(CS)                   Shariqa Ahmad   20     7.0   
42  022-14-110587  BS(CS)                   Sumbul Rehman   28     5.0   
43  022-14-110451  BS(CS)               Syed Faizan Uddin   28     9.0   
44  022-14-110589  BS(CS)                     Syed Sohaib   25     7.0   
45  022-14-110400  BS(CS)               Syeda Sabika Raza   27     9.0   
46   022-14-19911  BS(CS)                      Usman Khan   25     8.0   
47  022-14-110219  BS(CS)                     Waqar Ahmed   11     9.0   

    Quiz 2  Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
0      3.0                8           7.0           9.0                    9   
1      5.0                5           8.0          10.0                   10   
2      2.0                5           8.0          10.0                   10   
3      2.0                7           NaN           2.0   

In [148]:
df.shape

(48, 14)

In [149]:
df.columns

Index(['Student Code', 'Degree', 'Student Name', 'Mid', 'Quiz 1', 'Quiz 2',
       'Best of Quizzes', 'Assignment 1', 'Assignment 2',
       'Best of Assignments', 'Total Sessional (50)', 'Final (50)',
       'Total (100)', 'Grade'],
      dtype='object')

In [152]:
df[df['Mid']>20].count()

Student Code            32
Degree                  32
Student Name            32
Mid                     32
Quiz 1                  32
Quiz 2                  30
Best of Quizzes         32
Assignment 1            32
Assignment 2            23
Best of Assignments     32
Total Sessional (50)    32
Final (50)              32
Total (100)             32
Grade                   32
dtype: int64

In [155]:
df[(df['Mid']>20) & (df['Best of Quizzes']>7) & (df['Best of Assignments']>7)]

Student Code  Degree         Student Name  Mid  Quiz 1  Quiz 2  \
0    022-14-19987  BS(CS)          Abdul Basit   28     8.0     3.0   
5   022-14-110232  BS(CS)          Ameer Hamza   25     9.0     6.0   
7   022-14-110388  BS(CS)     Aneebullah Niazi   26     9.0     6.0   
9   022-14-110599  BS(CS)              Arsalan   28     8.0     6.0   
10  022-14-110214  BS(CS)  Fatima Haider Warsi   30     8.0     7.0   
13  022-14-110600  BS(CS)   Hamza Abdul Jabbar   24     8.0     4.0   
19  022-14-110222  BS(CS)      Mohammad Hunain   27     9.0     6.0   
25  022-14-110105  BS(CS)       Muhammad Faraz   26     9.0     6.0   
27  022-14-110452  BS(CS)  Muhammad Osama Khan   27     8.0     6.0   
30  022-14-110401  BS(CS)      Muhammad Shozab   23     8.0     6.0   
34  022-14-110413  BS(CS)     Nazeer Bin Zafar   25     9.0     6.0   
36  022-14-110582  BS(CS)           Rida Nasim   25     9.0     5.0   
37  022-14-110230  BS(CS)        Sadaf Nosheen   27     9.0     5.0   
40  022-14-110584  BS(CS)          Sharif Taqi   27     9.0     6.0   
43  022-14-110451  BS(CS)    Syed Faizan Uddin   28     9.0     4.0   
45  022-14-110400  BS(CS)    Syeda Sabika Raza   27     9.0     6.0   
46   022-14-19911  BS(CS)           Usman Khan   25     8.0     5.0   

    Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
0                 8           7.0           9.0                    9   
5                 9           8.0          10.0                   10   
7                 9           8.0          10.0                   10   
9                 8           8.0           NaN                    8   
10                8           8.0           NaN                    8   
13                8           8.0          10.0                   10   
19                9           8.0          10.0                   10   
25                9           8.0          10.0                   10   
27                8           8.0          10.0                   10   
30                8           9.0           NaN                    9   
34                9           8.0          10.0                   10   
36                9           9.0           NaN                    9   
37                9           9.0           NaN                    9   
40                9           8.0          10.0                   10   
43                9           6.0           8.0                    8   
45                9           9.0           NaN                    9   
46                8           8.0          10.0                   10   

    Total Sessional (50)  Final (50)  Total (100) Grade  
0                     45        25.0           70     B  
5                     44        27.0           71     B  
7                     45        40.0           85     A  
9                     44        40.0           84     A  
10                    46        45.0           91     A  
13                    42        25.0           67     C  
19                    46        45.0           91     A  
25                    45        41.0           86     A  
27                    45        26.0           71     B  
30                    40        32.0           72     B  
34                    44        42.0           86     A  
36                    43        27.0           70     B  
37                    45        30.0           75     B  
40                    46        35.0           81     A  
43                    45        34.0           79     B  
45                    45        35.0           80     A  
46                    43        22.0           65     C

In [157]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 14 columns):
Student Code            48 non-null object
Degree                  48 non-null object
Student Name            48 non-null object
Mid                     48 non-null int64
Quiz 1                  45 non-null float64
Quiz 2                  45 non-null float64
Best of Quizzes         48 non-null int64
Assignment 1            45 non-null float64
Assignment 2            36 non-null float64
Best of Assignments     48 non-null int64
Total Sessional (50)    48 non-null int64
Final (50)              47 non-null float64
Total (100)             48 non-null int64
Grade                   48 non-null object
dtypes: float64(5), int64(5), object(4)
memory usage: 5.3+ KB


In [158]:
df

Student Code  Degree                    Student Name  Mid  Quiz 1  \
0    022-14-19987  BS(CS)                     Abdul Basit   28     8.0   
1   022-14-110233  BS(CS)                     Adeel Ahmed   17     NaN   
2   022-14-110585  BS(CS)                    Afrah Zareen   18     5.0   
3    022-14-19718  BS(CS)                  Ahmed Ali Raza   14     7.0   
4   022-14-110648  BS(CS)                 Ahsan Ali Vohra   27     7.0   
5   022-14-110232  BS(CS)                     Ameer Hamza   25     9.0   
6   022-14-110588  BS(CS)                   Anas Ali Khan   28     5.0   
7   022-14-110388  BS(CS)                Aneebullah Niazi   26     9.0   
8   022-14-110601  BS(CS)                  Areesha Sohail   19     9.0   
9   022-14-110599  BS(CS)                         Arsalan   28     8.0   
10  022-14-110214  BS(CS)             Fatima Haider Warsi   30     8.0   
11  022-14-110591  BS(CS)                     Habib Ullah   28     8.0   
12  022-15-110994  BS(CS)             Hafiza Tooba Akbani   23     7.0   
13  022-14-110600  BS(CS)              Hamza Abdul Jabbar   24     8.0   
14  022-14-110389  BS(CS)                   Hareem Afshan   21     7.0   
15   022-14-19916  BS(CS)                    Haseeb Sajid   18     NaN   
16  022-14-110596  BS(CS)                    Hassam Ahmed   23     5.0   
17  022-14-110396  BS(CS)                    Khalid Anwer   20     8.0   
18  022-14-110223  BS(CS)                   Madiha Jabeen   16     5.0   
19  022-14-110222  BS(CS)                 Mohammad Hunain   27     9.0   
20  022-14-110412  BS(CS)                  Muhammad Aamir   24     7.0   
21  022-14-110593  BS(CS)  Muhammad Abdul Rehman Siddiqui   20     9.0   
22  022-14-110398  BS(CS)               Muhammad Abdullah   20     7.0   
23   022-14-19983  BS(CS)              Muhammad Ali Iqbal   26     5.0   
24  022-14-110215  BS(CS)                  Muhammad Bilal   28     5.0   
25  022-14-110105  BS(CS)                  Muhammad Faraz   26     9.0   
26  022-14-110370  BS(CS)         Muhammad Ghazali Faridi   27     6.0   
27  022-14-110452  BS(CS)             Muhammad Osama Khan   27     8.0   
28  022-14-110387  BS(CS)          Muhammad Saqib Intizar   22     6.0   
29  022-14-110217  BS(CS)       Muhammad Shahroz Khurshid   17     7.0   
30  022-14-110401  BS(CS)                 Muhammad Shozab   23     8.0   
31  022-14-110231  BS(CS)           Muhammad Taha Hasnain   27     7.0   
32  022-14-110035  BS(CS)           Muhammad Wajahat Khan    9     NaN   
33   022-14-19919  BS(CS)            Muhammad Younus Baig   20     4.0   
34  022-14-110413  BS(CS)                Nazeer Bin Zafar   25     9.0   
35   022-14-19923  BS(CS)                      Rabi Ahmed   20     8.0   
36  022-14-110582  BS(CS)                      Rida Nasim   25     9.0   
37  022-14-110230  BS(CS)                   Sadaf Nosheen   27     9.0   
38  022-14-110229  BS(CS)                Sadaquat Rafique    9     6.0   
39  022-14-110107  BS(CS)                     Sania Iqbal   28     4.0   
40  022-14-110584  BS(CS)                     Sharif Taqi   27     9.0   
41  022-14-110225  BS(CS)                   Shariqa Ahmad   20     7.0   
42  022-14-110587  BS(CS)                   Sumbul Rehman   28     5.0   
43  022-14-110451  BS(CS)               Syed Faizan Uddin   28     9.0   
44  022-14-110589  BS(CS)                     Syed Sohaib   25     7.0   
45  022-14-110400  BS(CS)               Syeda Sabika Raza   27     9.0   
46   022-14-19911  BS(CS)                      Usman Khan   25     8.0   
47  022-14-110219  BS(CS)                     Waqar Ahmed   11     9.0   

    Quiz 2  Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
0      3.0                8           7.0           9.0                    9   
1      5.0                5           8.0          10.0                   10   
2      2.0                5           8.0          10.0                   10   
3      2.0                7           NaN           2.0   

In [163]:
df1=df.copy()

In [165]:



df1['Quiz 1'].fillna(df1['Quiz 1'].mean(),inplace=True)

In [166]:
df1

Student Code  Degree                    Student Name  Mid    Quiz 1  \
0    022-14-19987  BS(CS)                     Abdul Basit   28  8.000000   
1   022-14-110233  BS(CS)                     Adeel Ahmed   17  7.288889   
2   022-14-110585  BS(CS)                    Afrah Zareen   18  5.000000   
3    022-14-19718  BS(CS)                  Ahmed Ali Raza   14  7.000000   
4   022-14-110648  BS(CS)                 Ahsan Ali Vohra   27  7.000000   
5   022-14-110232  BS(CS)                     Ameer Hamza   25  9.000000   
6   022-14-110588  BS(CS)                   Anas Ali Khan   28  5.000000   
7   022-14-110388  BS(CS)                Aneebullah Niazi   26  9.000000   
8   022-14-110601  BS(CS)                  Areesha Sohail   19  9.000000   
9   022-14-110599  BS(CS)                         Arsalan   28  8.000000   
10  022-14-110214  BS(CS)             Fatima Haider Warsi   30  8.000000   
11  022-14-110591  BS(CS)                     Habib Ullah   28  8.000000   
12  022-15-110994  BS(CS)             Hafiza Tooba Akbani   23  7.000000   
13  022-14-110600  BS(CS)              Hamza Abdul Jabbar   24  8.000000   
14  022-14-110389  BS(CS)                   Hareem Afshan   21  7.000000   
15   022-14-19916  BS(CS)                    Haseeb Sajid   18  7.288889   
16  022-14-110596  BS(CS)                    Hassam Ahmed   23  5.000000   
17  022-14-110396  BS(CS)                    Khalid Anwer   20  8.000000   
18  022-14-110223  BS(CS)                   Madiha Jabeen   16  5.000000   
19  022-14-110222  BS(CS)                 Mohammad Hunain   27  9.000000   
20  022-14-110412  BS(CS)                  Muhammad Aamir   24  7.000000   
21  022-14-110593  BS(CS)  Muhammad Abdul Rehman Siddiqui   20  9.000000   
22  022-14-110398  BS(CS)               Muhammad Abdullah   20  7.000000   
23   022-14-19983  BS(CS)              Muhammad Ali Iqbal   26  5.000000   
24  022-14-110215  BS(CS)                  Muhammad Bilal   28  5.000000   
25  022-14-110105  BS(CS)                  Muhammad Faraz   26  9.000000   
26  022-14-110370  BS(CS)         Muhammad Ghazali Faridi   27  6.000000   
27  022-14-110452  BS(CS)             Muhammad Osama Khan   27  8.000000   
28  022-14-110387  BS(CS)          Muhammad Saqib Intizar   22  6.000000   
29  022-14-110217  BS(CS)       Muhammad Shahroz Khurshid   17  7.000000   
30  022-14-110401  BS(CS)                 Muhammad Shozab   23  8.000000   
31  022-14-110231  BS(CS)           Muhammad Taha Hasnain   27  7.000000   
32  022-14-110035  BS(CS)           Muhammad Wajahat Khan    9  7.288889   
33   022-14-19919  BS(CS)            Muhammad Younus Baig   20  4.000000   
34  022-14-110413  BS(CS)                Nazeer Bin Zafar   25  9.000000   
35   022-14-19923  BS(CS)                      Rabi Ahmed   20  8.000000   
36  022-14-110582  BS(CS)                      Rida Nasim   25  9.000000   
37  022-14-110230  BS(CS)                   Sadaf Nosheen   27  9.000000   
38  022-14-110229  BS(CS)                Sadaquat Rafique    9  6.000000   
39  022-14-110107  BS(CS)                     Sania Iqbal   28  4.000000   
40  022-14-110584  BS(CS)                     Sharif Taqi   27  9.000000   
41  022-14-110225  BS(CS)                   Shariqa Ahmad   20  7.000000   
42  022-14-110587  BS(CS)                   Sumbul Rehman   28  5.000000   
43  022-14-110451  BS(CS)               Syed Faizan Uddin   28  9.000000   
44  022-14-110589  BS(CS)                     Syed Sohaib   25  7.000000   
45  022-14-110400  BS(CS)               Syeda Sabika Raza   27  9.000000   
46   022-14-19911  BS(CS)                      Usman Khan   25  8.000000   
47  022-14-110219  BS(CS)                     Waqar Ahmed   11  9.000000   

    Quiz 2  Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
0      3.0                8           7.0           9.0                    9   
1      5.0                5           8.0          10.0                   10   
2      2.0                5           8.

In [ ]:
df.mean