In [2]:
import numpy as np

In [27]:
oneD = np.array([1,7,8,9])

In [28]:
oneD

array([1, 7, 8, 9])

In [29]:
type(oneD)

numpy.ndarray

In [30]:
oneD.ndim

1

In [31]:
oneD.shape

(4,)

In [32]:
zeeroD = np.array(100)  # scaler or zeero dimemsional tensor

In [18]:
zeeroD.ndim


0

In [19]:
zeeroD.shape

()

In [33]:
twoD = np.array([[[[[[[[[[[[[[[[[[100]]]]]]]]]]]]]]]]]])

In [34]:
twoD.ndim

18

In [23]:
twoD.shape

(1, 1, 1)

In [24]:
twoD2 = np.array([[1,2,3,4],[4,3,2,1],[4,5,6,7]])

In [25]:
twoD2.shape

(3, 4)

In [51]:
oneD = np.arange(10)

In [52]:
oneD

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
twoD = np.arange(13).reshape(13,1)

In [54]:
twoD

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [57]:
threeD = np.array([[[1,2,3],[4,5,6],[7,7,8]],[[3,3,3],[4,4,4],[6,6,6]]])

In [58]:
threeD

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 7, 8]],

       [[3, 3, 3],
        [4, 4, 4],
        [6, 6, 6]]])

In [59]:
threeD.shape

(2, 3, 3)

In [62]:
threeD = np.arange(100).reshape(4,5,5)

In [63]:
threeD

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [66]:

#(3,4,2)
ex = np.array([[[1,2],[1,3],[4,5],[6,7]],[[1,2],[1,3],[4,5],[6,7]],[[1,2],[1,3],[4,5],[6,7]]])

In [67]:
ex.shape

(3, 4, 2)

# Data type

In [74]:
a = np.array([1.5,2.5,3.6,4.87],dtype = "int32")

In [75]:
a.dtype

dtype('int32')

In [76]:
a

array([1, 2, 3, 4])

In [77]:
a = np.array([1.5,2.5,3.6,4.87],dtype = np.int8)

In [78]:
a

array([1, 2, 3, 4], dtype=int8)

In [83]:
a= a.astype("float64")

In [84]:
a

array([1., 2., 3., 4.])

In [91]:
aList = [1,2,3,4,5,6,7,8,9]
aList

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [86]:
bList = []
for num in aList:
    bList.append(num*5)
bList

[5, 10, 15, 20, 25, 30, 35, 40, 45]

In [96]:
aList  = np.arange(1,21).reshape(4,5)

In [97]:
aList

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [94]:
aList *5

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [95]:
aList + aList

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [100]:
t1 = np.random.randn(2,3)*10

In [101]:
t1

array([[  1.67061851,   9.18027   ,   0.13972787],
       [  3.42062094, -13.23385926,  12.57606744]])

In [116]:
t2 = np.random.randn(2,3)*100
t2

array([[ 54.62385145, -52.77115491,  59.83498972],
       [ 17.85722634, 138.3112812 ,  14.4134023 ]])

In [117]:
t1 + t2

array([[ 56.29446997, -43.59088491,  59.97471759],
       [ 21.27784728, 125.07742194,  26.98946975]])

In [118]:
t1.shape == t2.shape

True

In [119]:
t1 - t2

array([[ -52.95323294,   61.95142492,  -59.69526185],
       [ -14.4366054 , -151.54514047,   -1.83733486]])

In [120]:
t1 / t2

array([[ 0.03058405, -0.17396379,  0.00233522],
       [ 0.19155388, -0.09568171,  0.87252594]])

In [121]:
t1*t2

array([[   91.25561741,  -484.45345053,     8.36061553],
       [   61.08280229, -1830.39202977,   181.26391947]])

In [122]:
t1.shape

(2, 3)

In [123]:
t2.shape

(2, 3)

In [124]:
t3 = np.arange(9).reshape(3,3)

In [127]:
t1.shape, t3.shape

((2, 3), (3, 3))

In [128]:
 t3.shape, t1.shape

((3, 3), (2, 3))

In [129]:
t1@t3

array([[28.37917722, 39.3697936 , 50.36040999],
       [35.75482688, 38.517656  , 41.28048512]])

In [130]:
np.dot(t1,t3)

array([[28.37917722, 39.3697936 , 50.36040999],
       [35.75482688, 38.517656  , 41.28048512]])

In [131]:
t1.dot(t3)

array([[28.37917722, 39.3697936 , 50.36040999],
       [35.75482688, 38.517656  , 41.28048512]])

In [133]:
zeeros = np.zeros((10,10))
zeeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [136]:
ones  = np.ones((5,5))*10

In [137]:
ones

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [140]:
fulll = np.full((10,10), 3)

In [141]:
fulll

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [142]:
empty = np.empty((4,4))

In [143]:
empty

array([[4.67296746e-307, 1.69121096e-306, 2.22520559e-306,
        1.11261162e-306],
       [1.42418987e-306, 1.37961641e-306, 1.60220528e-306,
        1.24611266e-306],
       [9.34598925e-307, 1.24612081e-306, 1.11260755e-306,
        1.60220393e-306],
       [1.51320640e-306, 9.34609790e-307, 1.86921279e-306,
        1.24610723e-306]])

In [144]:
eye = np.eye(4,5)

In [145]:
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [147]:
onesLike = np.ones_like(t1)


In [148]:
onesLike

array([[1., 1., 1.],
       [1., 1., 1.]])

In [150]:
t1

array([[  1.67061851,   9.18027   ,   0.13972787],
       [  3.42062094, -13.23385926,  12.57606744]])

In [153]:
t1>5

[array([[False,  True, False],
        [False, False,  True]])]

In [154]:
t1[t1<5]

array([  1.67061851,   0.13972787,   3.42062094, -13.23385926])

# Basic Indexing and Slicing

In [155]:
alist = [1,2,3,4,5,6,7,8,9]

In [156]:
alist[5]

6

In [157]:
type(alist[5])

int

In [158]:
alist[1:5]

[2, 3, 4, 5]

In [160]:
type(alist[5:6])

list

In [161]:
alist[5:6]

[6]

In [162]:
twoD = np.arange(100).reshape(10,10)

In [163]:
twoD

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [167]:
twoD[5,4]  #

54

In [165]:
twoD[5][4]

54

In [166]:
#twoD[row, column]
#twoD[start:end, start:end]
twoD[3:7,4:7]

array([[34, 35, 36],
       [44, 45, 46],
       [54, 55, 56],
       [64, 65, 66]])

In [169]:
twoD[8:,4:6]

array([[84, 85],
       [94, 95]])

In [170]:
twoD[:,9]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])