# Numpy 3D arrays

In [5]:
import numpy as np

d3 = np.arange(50).reshape(2,5,5)
d3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

Indexing 3D

In [6]:
d3[1,2,1]

36

In [7]:
d3[1]

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [15]:
d3[0:,2:,1:3]

array([[[11, 12],
        [16, 17],
        [21, 22]],

       [[36, 37],
        [41, 42],
        [46, 47]]])

In [12]:
#d3[1:2,4:5,0:5]
d3[1:,4:,:]

array([[[45, 46, 47, 48, 49]]])

In [ ]:
### d3[0:,2:4,1:3]

In [18]:
d3[1,:,3:4]

array([[28],
       [33],
       [38],
       [43],
       [48]])

# BroadCasting

In [31]:
x = np.array([[1,2,3]])  #(1,3)
y = np.array([[1],[2],[3]])#(3,1)
x+y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [25]:
x.shape, y.shape

((1, 3), (3, 1))

In [27]:
x,y=np.broadcast_arrays(x,y)
x 

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [28]:
y

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [29]:
x+y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

# Pandas

# Pandas data structure
Series
DataFrame

# Series

In [32]:
import pandas as pd

In [36]:
s = pd.Series([111,222,333,444,555,666,777])
s  # pandas series object

0    111
1    222
2    333
3    444
4    555
5    666
6    777
dtype: int64

In [37]:
# labels/index and values

In [38]:
#getting a single series value

s[4]

555

In [40]:
#getting a single series value
s[[5,0,3,1]]

5    666
0    111
3    444
1    222
dtype: int64

In [43]:
# updating a series value
s[3]= 1000
# updating multiple series value

s[[2,4,0]]=[9999,7777,1111]

In [44]:
s

0    1111
1     222
2    9999
3    1000
4    7777
5     666
6     777
dtype: int64

In [45]:
# deleting a value in series

del s[4]
s

0    1111
1     222
2    9999
3    1000
5     666
6     777
dtype: int64

In [46]:
# deleting multiple values in a series
del s[[0,2,6]]

# not allowed

TypeError: '[0, 2, 6]' is an invalid key

In [50]:
s[1234]= 45676878
s[[123,345,678]]=[23,23,23]
#not allowed

ValueError: [123 345 678] not contained in the index

In [51]:
s

0           1111
1            222
2           9999
3           1000
5            666
6            777
1234    45676878
dtype: int64

In [52]:
s1 = pd.Series([100,200,300,400], index=["apples", "oranges","bananas", "grapes"])

In [53]:
s1

apples     100
oranges    200
bananas    300
grapes     400
dtype: int64

# Creating a series using a dictionary

In [54]:
aDic = {"name":"Nasir Hussain", "Class":"AI", "Time":"5-9"}

In [56]:
aDic

{'name': 'Nasir Hussain', 'Class': 'AI', 'Time': '5-9'}

In [57]:
s2 = pd.Series(aDic)
s2

name     Nasir Hussain
Class               AI
Time               5-9
dtype: object

In [60]:
s3 = pd.Series(s1, index=["mango", "oranges","bananas", "grapes"])

In [61]:
s3

mango        NaN
oranges    200.0
bananas    300.0
grapes     400.0
dtype: float64

In [62]:
s3["mango"]=100

In [63]:
s3

mango      100.0
oranges    200.0
bananas    300.0
grapes     400.0
dtype: float64

In [64]:
s3.values

array([100., 200., 300., 400.])

In [65]:
s3.index

Index(['mango', 'oranges', 'bananas', 'grapes'], dtype='object')

In [67]:
s3[s3>200]

bananas    300.0
grapes     400.0
dtype: float64

In [68]:
s3>200

mango      False
oranges    False
bananas     True
grapes      True
dtype: bool

In [70]:
"Mango" in s3

False

In [71]:
s4= pd.Series(s3.values, index=[22,33,44,55])

In [72]:
s4

22    100.0
33    200.0
44    300.0
55    400.0
dtype: float64

In [73]:
s3

mango      100.0
oranges    200.0
bananas    300.0
grapes     400.0
dtype: float64

In [74]:
s3+s4

/home/nasir/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py:3772: RuntimeWarning: '<' not supported between instances of 'str' and 'int', sort order is undefined for incomparable objects
  return this.join(other, how=how, return_indexers=return_indexers)


mango     NaN
oranges   NaN
bananas   NaN
grapes    NaN
22        NaN
33        NaN
44        NaN
55        NaN
dtype: float64

# DataFrame

In [75]:
df = pd.DataFrame([123,234,345,456])
df

0
0  123
1  234
2  345
3  456

In [79]:
df = pd.DataFrame(["Red","Green", "Blue"],index=['v1','v2','v3'])
df

0
v1    Red
v2  Green
v3   Blue

In [80]:
df = pd.DataFrame(["Red","Green", "Blue"],index=['v1','v2','v3'],columns=["Colors"])
df

Colors
v1    Red
v2  Green
v3   Blue

# Creating a Data Frame from a dictionary

In [122]:
score = {"Ai for EO":[76,78,89,90,83,82,87,89,90,99],
         "Python1"  :[67,78,76,75,89,90,54,78,87,45],
         "Python2"  :[78,76,79,56,34,89,45,78,91,89]
        }

In [123]:
df = pd.DataFrame(score,index=["Nasir", "Asad","Ahmed",
                               "Abdullah","Faraz", "Zaid",
                               "Ali", "Khan", 'Faisal', 
                               "Fahad"])
df

Ai for EO  Python1  Python2
Nasir            76       67       78
Asad             78       78       76
Ahmed            89       76       79
Abdullah         90       75       56
Faraz            83       89       34
Zaid             82       90       89
Ali              87       54       45
Khan             89       78       78
Faisal           90       87       91
Fahad            99       45       89

In [124]:
df.head(3)

Ai for EO  Python1  Python2
Nasir         76       67       78
Asad          78       78       76
Ahmed         89       76       79

In [125]:
df.tail(3)

Ai for EO  Python1  Python2
Khan           89       78       78
Faisal         90       87       91
Fahad          99       45       89

In [126]:
df

Ai for EO  Python1  Python2
Nasir            76       67       78
Asad             78       78       76
Ahmed            89       76       79
Abdullah         90       75       56
Faraz            83       89       34
Zaid             82       90       89
Ali              87       54       45
Khan             89       78       78
Faisal           90       87       91
Fahad            99       45       89

In [127]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, Nasir to Fahad
Data columns (total 3 columns):
Ai for EO    10 non-null int64
Python1      10 non-null int64
Python2      10 non-null int64
dtypes: int64(3)
memory usage: 320.0+ bytes


In [128]:
df.describe()

Ai for EO    Python1    Python2
count  10.000000  10.000000  10.000000
mean   86.300000  73.900000  71.500000
std     6.733828  14.820781  19.727308
min    76.000000  45.000000  34.000000
25%    82.250000  69.000000  61.000000
50%    88.000000  77.000000  78.000000
75%    89.750000  84.750000  86.500000
max    99.000000  90.000000  91.000000

In [129]:
#data = pd.read_csv("banknotes.csv")

In [130]:
df['Python1']

Nasir       67
Asad        78
Ahmed       76
Abdullah    75
Faraz       89
Zaid        90
Ali         54
Khan        78
Faisal      87
Fahad       45
Name: Python1, dtype: int64

In [131]:
df['Ai for EO']

Nasir       76
Asad        78
Ahmed       89
Abdullah    90
Faraz       83
Zaid        82
Ali         87
Khan        89
Faisal      90
Fahad       99
Name: Ai for EO, dtype: int64

In [132]:
df.loc[['Abdullah','Fahad']]['Python1']

Abdullah    75
Fahad       45
Name: Python1, dtype: int64

In [133]:
df

Ai for EO  Python1  Python2
Nasir            76       67       78
Asad             78       78       76
Ahmed            89       76       79
Abdullah         90       75       56
Faraz            83       89       34
Zaid             82       90       89
Ali              87       54       45
Khan             89       78       78
Faisal           90       87       91
Fahad            99       45       89

In [134]:
df["extra"]=range(10)
df

Ai for EO  Python1  Python2  extra
Nasir            76       67       78      0
Asad             78       78       76      1
Ahmed            89       76       79      2
Abdullah         90       75       56      3
Faraz            83       89       34      4
Zaid             82       90       89      5
Ali              87       54       45      6
Khan             89       78       78      7
Faisal           90       87       91      8
Fahad            99       45       89      9

In [135]:
del df["extra"]
df

Ai for EO  Python1  Python2
Nasir            76       67       78
Asad             78       78       76
Ahmed            89       76       79
Abdullah         90       75       56
Faraz            83       89       34
Zaid             82       90       89
Ali              87       54       45
Khan             89       78       78
Faisal           90       87       91
Fahad            99       45       89

In [136]:
df["Total"]=df["Ai for EO"] + df["Python1"] + df['Python2']
df

Ai for EO  Python1  Python2  Total
Nasir            76       67       78    221
Asad             78       78       76    232
Ahmed            89       76       79    244
Abdullah         90       75       56    221
Faraz            83       89       34    206
Zaid             82       90       89    261
Ali              87       54       45    186
Khan             89       78       78    245
Faisal           90       87       91    268
Fahad            99       45       89    233

In [141]:
# df["Status"]=np.where(df['Total']>200,"Pass","Fail")
# df



In [142]:
df["Status"]=["Pass" if marks>200 else "Fails" for marks in df['Total']]

In [143]:
df

Ai for EO  Python1  Python2  Total Status
Nasir            76       67       78    221   Pass
Asad             78       78       76    232   Pass
Ahmed            89       76       79    244   Pass
Abdullah         90       75       56    221   Pass
Faraz            83       89       34    206   Pass
Zaid             82       90       89    261   Pass
Ali              87       54       45    186  Fails
Khan             89       78       78    245   Pass
Faisal           90       87       91    268   Pass
Fahad            99       45       89    233   Pass

In [145]:
df['RevisedStatus']=np.where(((df['Ai for EO']>=50) & (df["Python1"]>=50) & (df["Python2"]>=50)),"Pass","Fail")

In [146]:
df

Ai for EO  Python1  Python2  Total Status RevisedStatus
Nasir            76       67       78    221   Pass          Pass
Asad             78       78       76    232   Pass          Pass
Ahmed            89       76       79    244   Pass          Pass
Abdullah         90       75       56    221   Pass          Pass
Faraz            83       89       34    206   Pass          Fail
Zaid             82       90       89    261   Pass          Pass
Ali              87       54       45    186  Fails          Fail
Khan             89       78       78    245   Pass          Pass
Faisal           90       87       91    268   Pass          Pass
Fahad            99       45       89    233   Pass          Fail

In [147]:
df['newStatus']=["Pass" if (ai>=50) & (p1>=50) & (p2>=50) else "Fail" for ai,p1,p2 in zip(df["Ai for EO"], df['Python1'],df["Python2"])]

In [148]:
df

Ai for EO  Python1  Python2  Total Status RevisedStatus newStatus
Nasir            76       67       78    221   Pass          Pass      Pass
Asad             78       78       76    232   Pass          Pass      Pass
Ahmed            89       76       79    244   Pass          Pass      Pass
Abdullah         90       75       56    221   Pass          Pass      Pass
Faraz            83       89       34    206   Pass          Fail      Fail
Zaid             82       90       89    261   Pass          Pass      Pass
Ali              87       54       45    186  Fails          Fail      Fail
Khan             89       78       78    245   Pass          Pass      Pass
Faisal           90       87       91    268   Pass          Pass      Pass
Fahad            99       45       89    233   Pass          Fail      Fail

In [149]:
x = [1,2,3,4]
y = ['a','b','c','d']
z = zip(x,y)


In [150]:
for x,y in z:
    print(x,y)

1 a
2 b
3 c
4 d


# 0332-3446734